### ISSUE TITLE
Undefined index: q

### ISSUE THREAD

**Issue by vishvega** [mikecao/shorty#10]
I followed the guide, added database and htdocs.
But I still get this error.

> Notice: Undefined index: q in C:\xampp\htdocs\shorty\shorty.php on line 314
> 404 Not Found

this is my project path : C:\xampp\htdocs\shorty
this is my htdocs path : C:\xampp\htdocs\shorty\.htdocs

this is my config file.
```
<?php
// Hostname for your URL shortener
$hostname = 'http://localhost.com';
// PDO connection to the database
$connection = new PDO('mysql:dbname=shorty_temp;host=localhost', 'root', '');
$chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
$salt = '';
$padding = 3;
?>
```

how can I fix this?

**Comment by jacobsandersen** [comment]
You're not supplying the URL to shorten in 'q'.

**Comment by jacobsandersen** [comment]
@mikecao recommend closure
